### PR TITLE
moving classes to a more component like structure

### PR DESCRIPTION
**Pull request by wickedOne**
- add Wikipedia and YouTube namespace and moved applicable classes. this way the code is clustered by implementation making it easier to copy paste it to your own application.

### CODE REVIEW

**Comment by chr-hertel** [comment]
Yes, nice idea! What do you think of dropping Rag in favor of Blog?

Wikipedia example is basically also Rag but thats only a Pattern and the real use case is around the Blog.

Just got me thinking ...

**Comment by wickedOne** [comment]
yes, that makes perfectly sense indeed

**Comment by chr-hertel** [comment]
Let me know if you want to follow up, otherwise i will merge later when I'm back at my laptop and continue :)

**Comment by wickedOne** [comment]
yes, i'll follow up. 

another question would be: are you intending to add more implementation examples to this repository?
if so, perhaps having a parent namespace `Implementation` for `YouTube`, `Blog`, `Wikipedia` makes sense?

**Comment by chr-hertel** [comment]
No, not yet, at least nö further plans atm

**Comment by wickedOne** [comment]
alright then, changes pushed...

**Review by chr-hertel — APPROVED** [review]
Thanks, great impulse to encapsulate in namespaces for easier understanding, will follow up on the frontend stuff :+1:

**Comment by wickedOne** [comment]
oops, yes sloppy me forgot about the templates... :pensive:

**Pull request merged**
